/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.5 and the DSP System Toolbox 9.0.
 * Generated on: 17-May-2015 21:40:41
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 102
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 * Arithmetic        : single
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /usr/local/share/MATLAB/extern/include/tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int BL = 102;
const int16_T B[102] = {
       -5,    -27,    -71,   -138,   -213,   -269,   -273,   -207,    -82,
       58,    155,    162,     76,    -55,   -155,   -161,    -62,     87,
      191,    177,     42,   -138,   -245,   -197,     -7,    213,    315,
      212,    -52,   -318,   -400,   -215,    150,    466,    505,    193,
     -311,   -684,   -639,   -124,    594,   1047,    842,    -53,  -1202,
    -1851,  -1305,    668,   3628,   6589,   8435,   8435,   6589,   3628,
      668,  -1305,  -1851,  -1202,    -53,    842,   1047,    594,   -124,
     -639,   -684,   -311,    193,    505,    466,    150,   -215,   -400,
     -318,    -52,    212,    315,    213,     -7,   -197,   -245,   -138,
       42,    177,    191,     87,    -62,   -161,   -155,    -55,     76,
      162,    155,     58,    -82,   -207,   -273,   -269,   -213,   -138,
      -71,    -27,     -5
};
