/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.5 and the DSP System Toolbox 9.0.
 * Generated on: 24-May-2015 18:02:00
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 7
 * Denominator Length  : 7
 * Stable              : Yes
 * Linear Phase        : No
 * Arithmetic          : single
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /usr/local/share/MATLAB/extern/include/tmwtypes.h 
 */
const int NL = 7;
const real32_T NUM[7] = {
   0.002998647979,-0.005114480387, 0.008418506943,-0.007476789877, 0.008418506943,
  -0.005114480387, 0.002998647979
};
const int DL = 7;
const real32_T DEN[7] = {
                1,   -4.815583229,    10.22179317,   -12.14486313,    8.490223885,
     -3.306707144,    0.560890615
};
